## Retail Fraud Detection

#### Life cycle of Machine learning Project

- Understanding the Problem Statement
- Data Collection
- Data Checks to perform
- Exploratory data analysis
- Data Pre-Processing
- Model Training
- Choose best model

### 1) Problem statement
- This project understands how the retail fraud can be detected.


### 2) Data Collection
- Dataset Source - https://www.kaggle.com/datasets/noopurbhatt/retail-intelligence-fraud-detection-dataset/data
- The data consists of 21 column and 100,000 rows.

### 2.1 Import Data and Required Packages
####  Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#### Import the CSV Data as Pandas DataFrame

In [2]:
df = pd.read_csv('Dataset/retail_fraud_detection_100K.csv')

In [3]:
df.head()

,transaction_id,customer_id,transaction_timestamp,transaction_amount,payment_method,device_type,location,merchant_category,is_international,transaction_frequency_24h,...,failed_transaction_count_24h,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk
0,T0000001,C20953,2026-03-04 19:56:23.679173,56.31,Debit Card,Tablet,Canada,Fashion,0,13,...,4,1054,0,0,0,1,0,1,0,Medium
1,T0000002,C24133,2026-03-09 19:56:23.679330,20.35,Credit Card,Tablet,India,Electronics,0,3,...,2,97,0,0,0,0,0,0,0,Low
2,T0000003,C07165,2026-01-01 19:56:23.679362,48.72,Debit Card,Tablet,UK,Travel,0,8,...,4,779,1,0,0,0,0,0,0,Medium
3,T0000004,C19310,2025-12-09 19:56:23.679385,153.62,Debit Card,Mobile,Australia,Fashion,0,14,...,3,286,1,1,0,1,0,1,1,High
4,T0000005,C25019,2025-11-09 19:56:23.679409,115.32,PayPal,Mobile,India,Gaming,0,10,...,3,866,0,0,0,1,0,0,0,Low

In [22]:
df['merchant_category'].unique()

array(['Fashion', 'Electronics', 'Travel', 'Gaming', 'Luxury',
       'Groceries'], dtype=object)

### 3. Data Checks to perform

- Check Missing values
- Check Duplicates
- Check data type
- Check the number of unique values of each column
- Check statistics of data set
- Check various categories present in the different categorical column

In [23]:
df.isna().sum()

transaction_id                      0
customer_id                         0
transaction_timestamp               0
transaction_amount                  0
payment_method                      0
device_type                         0
location                            0
merchant_category                   0
is_international                    0
transaction_frequency_24h           0
avg_transaction_amount_7d           0
failed_transaction_count_24h        0
account_age_days                    0
previous_fraud_flag                 0
unusual_amount_flag                 0
unusual_location_flag               0
multiple_transactions_short_time    0
high_risk_device_flag               0
velocity_flag                       0
fraud_flag                          0
fraud_risk                          0
dtype: int64

#### There are no missing values in the data set

### 3.2 Check Duplicates

In [24]:
df.duplicated().sum()

np.int64(0)

#### There are no duplicates  values in the data set

## Remove unwanted columns

In [ ]:
drop_cols=['transaction_frequency_24h','avg_transaction_amount_7d']
df.drop(drop_cols,axis=1,inplace=True)

KeyError: "['transaction_frequency_24h', 'avg_transaction_amount_7d'] not found in axis"

In [31]:
df.drop('failed_transaction_count_24h',axis=1,inplace=True)

In [32]:
df.head()

,transaction_id,customer_id,transaction_timestamp,transaction_amount,payment_method,device_type,location,merchant_category,is_international,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk
0,T0000001,C20953,2026-03-04 19:56:23.679173,56.31,Debit Card,Tablet,Canada,Fashion,0,1054,0,0,0,1,0,1,0,Medium
1,T0000002,C24133,2026-03-09 19:56:23.679330,20.35,Credit Card,Tablet,India,Electronics,0,97,0,0,0,0,0,0,0,Low
2,T0000003,C07165,2026-01-01 19:56:23.679362,48.72,Debit Card,Tablet,UK,Travel,0,779,1,0,0,0,0,0,0,Medium
3,T0000004,C19310,2025-12-09 19:56:23.679385,153.62,Debit Card,Mobile,Australia,Fashion,0,286,1,1,0,1,0,1,1,High
4,T0000005,C25019,2025-11-09 19:56:23.679409,115.32,PayPal,Mobile,India,Gaming,0,866,0,0,0,1,0,0,0,Low

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   transaction_id                    100000 non-null  object
 1   customer_id                       100000 non-null  object
 2   transaction_timestamp             100000 non-null  object
 3   transaction_amount                100000 non-null  float64
 4   payment_method                    100000 non-null  object
 5   device_type                       100000 non-null  object
 6   location                          100000 non-null  object
 7   merchant_category                 100000 non-null  object
 8   is_international                  100000 non-null  int64
 9   account_age_days                  100000 non-null  int64
 10  previous_fraud_flag               100000 non-null  int64
 11  unusual_amount_flag               100000 non-null  int64
 12  unusual_location_flag             100000 non-null  int64
 13  multiple_transactions_short_time  100000 non-null  int64
 14  high_risk_device_flag             100000 non-null  int64
 15  velocity_flag                     100000 non-null  int64
 16  fraud_flag                        100000 non-null  int64
 17  fraud_risk                        100000 non-null  object
dtypes: float64(1), int64(9), object(8)
memory usage: 13.7+ MB

In [34]:
df.head(10)

,transaction_id,customer_id,transaction_timestamp,transaction_amount,payment_method,device_type,location,merchant_category,is_international,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk
0,T0000001,C20953,2026-03-04 19:56:23.679173,56.31,Debit Card,Tablet,Canada,Fashion,0,1054,0,0,0,1,0,1,0,Medium
1,T0000002,C24133,2026-03-09 19:56:23.679330,20.35,Credit Card,Tablet,India,Electronics,0,97,0,0,0,0,0,0,0,Low
2,T0000003,C07165,2026-01-01 19:56:23.679362,48.72,Debit Card,Tablet,UK,Travel,0,779,1,0,0,0,0,0,0,Medium
3,T0000004,C19310,2025-12-09 19:56:23.679385,153.62,Debit Card,Mobile,Australia,Fashion,0,286,1,1,0,1,0,1,1,High
4,T0000005,C25019,2025-11-09 19:56:23.679409,115.32,PayPal,Mobile,India,Gaming,0,866,0,0,0,1,0,0,0,Low
5,T0000006,C08668,2026-04-08 19:56:23.679445,41.31,Credit Card,Tablet,USA,Gaming,1,709,1,0,1,1,0,1,1,High
6,T0000007,C09607,2025-06-13 19:56:23.679479,54.75,Credit Card,Tablet,UK,Luxury,1,1909,0,0,1,1,0,1,1,Medium
7,T0000008,C07468,2025-12-03 19:56:23.679515,86.64,PayPal,Mobile,USA,Fashion,0,656,1,1,0,1,0,0,1,Medium
8,T0000009,C12131,2025-10-31 19:56:23.679541,22.44,Google Pay,Tablet,Canada,Luxury,0,325,0,0,0,0,0,0,0,Low
9,T0000010,C05608,2025-07-31 19:56:23.679563,99.42,Google Pay,Mobile,India,Fashion,0,907,1,0,0,1,0,0,1,Medium

In [35]:
## Feature Engineering
df['Date']=df['transaction_timestamp'].str.split('-').str[2]
df['Month']=df['transaction_timestamp'].str.split('-').str[1]
df['Year']=df['transaction_timestamp'].str.split('-').str[0]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   transaction_id                    100000 non-null  object
 1   customer_id                       100000 non-null  object
 2   transaction_timestamp             100000 non-null  object
 3   transaction_amount                100000 non-null  float64
 4   payment_method                    100000 non-null  object
 5   device_type                       100000 non-null  object
 6   location                          100000 non-null  object
 7   merchant_category                 100000 non-null  object
 8   is_international                  100000 non-null  int64
 9   account_age_days                  100000 non-null  int64
 10  previous_fraud_flag               100000 non-null  int64
 11  unusual_amount_flag               100000 non-null  int64
 12  unusual_location_flag             100000 non-null  int64
 13  multiple_transactions_short_time  100000 non-null  int64
 14  high_risk_device_flag             100000 non-null  int64
 15  velocity_flag                     100000 non-null  int64
 16  fraud_flag                        100000 non-null  int64
 17  fraud_risk                        100000 non-null  object
 18  Date                              100000 non-null  object
 19  Month                             100000 non-null  object
 20  Year                              100000 non-null  object
dtypes: float64(1), int64(9), object(11)
memory usage: 16.0+ MB

In [37]:
df.head()

,transaction_id,customer_id,transaction_timestamp,transaction_amount,payment_method,device_type,location,merchant_category,is_international,account_age_days,...,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk,Date,Month,Year
0,T0000001,C20953,2026-03-04 19:56:23.679173,56.31,Debit Card,Tablet,Canada,Fashion,0,1054,...,0,0,1,0,1,0,Medium,04 19:56:23.679173,03,2026
1,T0000002,C24133,2026-03-09 19:56:23.679330,20.35,Credit Card,Tablet,India,Electronics,0,97,...,0,0,0,0,0,0,Low,09 19:56:23.679330,03,2026
2,T0000003,C07165,2026-01-01 19:56:23.679362,48.72,Debit Card,Tablet,UK,Travel,0,779,...,0,0,0,0,0,0,Medium,01 19:56:23.679362,01,2026
3,T0000004,C19310,2025-12-09 19:56:23.679385,153.62,Debit Card,Mobile,Australia,Fashion,0,286,...,1,0,1,0,1,1,High,09 19:56:23.679385,12,2025
4,T0000005,C25019,2025-11-09 19:56:23.679409,115.32,PayPal,Mobile,India,Gaming,0,866,...,0,0,1,0,0,0,Low,09 19:56:23.679409,11,2025

In [38]:
df['Date']=df['Date'].str.split(' ').str[0]

In [44]:
df.head()

,transaction_id,customer_id,transaction_amount,payment_method,device_type,location,merchant_category,is_international,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk,Date,Month,Year
0,0000001,20953,56.31,Debit Card,Tablet,Canada,Fashion,0,1054,0,0,0,1,0,1,0,Medium,04,03,2026
1,0000002,24133,20.35,Credit Card,Tablet,India,Electronics,0,97,0,0,0,0,0,0,0,Low,09,03,2026
2,0000003,07165,48.72,Debit Card,Tablet,UK,Travel,0,779,1,0,0,0,0,0,0,Medium,01,01,2026
3,0000004,19310,153.62,Debit Card,Mobile,Australia,Fashion,0,286,1,1,0,1,0,1,1,High,09,12,2025
4,0000005,25019,115.32,PayPal,Mobile,India,Gaming,0,866,0,0,0,1,0,0,0,Low,09,11,2025

In [41]:
df.drop('transaction_timestamp',axis=1,inplace=True)

In [43]:
df['transaction_id'] = df['transaction_id'].str[1:]
df['customer_id'] = df['customer_id'].str[1:]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   transaction_id                    100000 non-null  object
 1   customer_id                       100000 non-null  object
 2   transaction_amount                100000 non-null  float64
 3   payment_method                    100000 non-null  object
 4   device_type                       100000 non-null  object
 5   location                          100000 non-null  object
 6   merchant_category                 100000 non-null  object
 7   is_international                  100000 non-null  int64
 8   account_age_days                  100000 non-null  int64
 9   previous_fraud_flag               100000 non-null  int64
 10  unusual_amount_flag               100000 non-null  int64
 11  unusual_location_flag             100000 non-null  int64
 12  multiple_transactions_short_time  100000 non-null  int64
 13  high_risk_device_flag             100000 non-null  int64
 14  velocity_flag                     100000 non-null  int64
 15  fraud_flag                        100000 non-null  int64
 16  fraud_risk                        100000 non-null  object
 17  Date                              100000 non-null  object
 18  Month                             100000 non-null  object
 19  Year                              100000 non-null  object
dtypes: float64(1), int64(9), object(10)
memory usage: 15.3+ MB

In [46]:
df['transaction_id'] = df['transaction_id'].astype(int)
df['customer_id'] = df['customer_id'].astype(int)
df['Transaction_Date'] = df['Date'].astype(int)
df['Transaction_Month'] = df['Month'].astype(int)
df['Transaction_Year'] = df['Year'].astype(int)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   transaction_id                    100000 non-null  int64
 1   customer_id                       100000 non-null  int64
 2   transaction_amount                100000 non-null  float64
 3   payment_method                    100000 non-null  object
 4   device_type                       100000 non-null  object
 5   location                          100000 non-null  object
 6   merchant_category                 100000 non-null  object
 7   is_international                  100000 non-null  int64
 8   account_age_days                  100000 non-null  int64
 9   previous_fraud_flag               100000 non-null  int64
 10  unusual_amount_flag               100000 non-null  int64
 11  unusual_location_flag             100000 non-null  int64
 12  multiple_transactions_short_time  100000 non-null  int64
 13  high_risk_device_flag             100000 non-null  int64
 14  velocity_flag                     100000 non-null  int64
 15  fraud_flag                        100000 non-null  int64
 16  fraud_risk                        100000 non-null  object
 17  Date                              100000 non-null  object
 18  Month                             100000 non-null  object
 19  Year                              100000 non-null  object
 20  Transaction_Date                  100000 non-null  int64
 21  Transaction_Month                 100000 non-null  int64
 22  Transaction_Year                  100000 non-null  int64
dtypes: float64(1), int64(14), object(8)
memory usage: 17.5+ MB

In [48]:
drop_cols = ['Date','Month','Year']
df.drop(drop_cols,axis=1,inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   transaction_id                    100000 non-null  int64
 1   customer_id                       100000 non-null  int64
 2   transaction_amount                100000 non-null  float64
 3   payment_method                    100000 non-null  object
 4   device_type                       100000 non-null  object
 5   location                          100000 non-null  object
 6   merchant_category                 100000 non-null  object
 7   is_international                  100000 non-null  int64
 8   account_age_days                  100000 non-null  int64
 9   previous_fraud_flag               100000 non-null  int64
 10  unusual_amount_flag               100000 non-null  int64
 11  unusual_location_flag             100000 non-null  int64
 12  multiple_transactions_short_time  100000 non-null  int64
 13  high_risk_device_flag             100000 non-null  int64
 14  velocity_flag                     100000 non-null  int64
 15  fraud_flag                        100000 non-null  int64
 16  fraud_risk                        100000 non-null  object
 17  Transaction_Date                  100000 non-null  int64
 18  Transaction_Month                 100000 non-null  int64
 19  Transaction_Year                  100000 non-null  int64
dtypes: float64(1), int64(14), object(5)
memory usage: 15.3+ MB

### 3.5 Check statistics of data set

In [50]:
df.describe()

,transaction_id,customer_id,transaction_amount,is_international,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,Transaction_Date,Transaction_Month,Transaction_Year
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,15039.37007,120.475407,0.498010,1005.329380,0.500150,0.229530,0.498010,0.427040,0.100960,0.283980,0.475080,15.771170,6.539630,2025.325290
std,28867.657797,8663.74667,119.787252,0.499999,573.313726,0.500002,0.420533,0.499999,0.494651,0.301277,0.450929,0.499381,8.807157,3.444806,0.468485
min,1.000000,1.00000,0.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2025.000000
25%,25000.750000,7564.00000,34.820000,0.000000,510.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,4.000000,2025.000000
50%,50000.500000,15065.00000,84.130000,0.000000,1004.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000,7.000000,2025.000000
75%,75000.250000,22513.00000,167.520000,1.000000,1501.250000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,23.000000,10.000000,2026.000000
max,100000.000000,30000.00000,1548.520000,1.000000,1999.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,31.000000,12.000000,2026.000000

In [55]:
df.to_csv('Dataset/Cleaned_Data.csv',index=False)